openapi: 3.0.3
info:
  title: Client and Advisor API
  description: API for managing Client and Advisor objects
  version: 1.0.0
security:
  - highpeak-userpool-authorizer: []
tags:
  - name: Clients
    description: Endpoints for managing clients
  - name: Advisors
    description: Endpoints for managing advisors
  - name: LTC Queries
    description: Endpoints for long-term care probability, type, cost, duration, and longevity predictions
paths:
  /clients:
    post:
      tags: [Clients]
      summary: Create a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        "201":
          description: Client created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
    options:
      tags: [Clients]
      summary: Get available HTTP methods for the /clients endpoint
      responses:
        "200":
          description: Successful response with allowed HTTP methods
          headers:
            Allow:
              schema:
                type: string
    put:
      tags: [Clients]
      summary: Replace a client by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        "200":
          description: Client replaced successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
    patch:
      tags: [Clients]
      summary: Update a client by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: Client updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
    delete:
      tags: [Clients]
      summary: Delete a client by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Client deleted successfully
  /advisors:
    post:
      tags: [Advisors]
      summary: Create a new advisor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advisor"
      responses:
        "201":
          description: Advisor created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advisor"
    options:
      tags: [Advisors]
      summary: Get available HTTP methods for the /advisors endpoint
      responses:
        "200":
          description: Successful response with allowed HTTP methods
          headers:
            Allow:
              schema:
                type: string
    put:
      tags: [Advisors]
      summary: Replace an advisor by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advisor"
      responses:
        "200":
          description: Advisor replaced successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advisor"
    patch:
      tags: [Advisors]
      summary: Update an advisor by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: Advisor updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advisor"
    delete:
      tags: [Advisors]
      summary: Delete an advisor by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Advisor deleted successfully
  /  /ltc/queries/probability:
    post:
      tags: [LTC Queries]
      summary: Estimate long-term care need probability
      description: Predicts the probability of needing long-term care.
      operationId: queryProbability
      parameters:
        - name: age
          in: query
          required: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          schema:
            type: string
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
        - name: overall_health_rating
          in: query
          required: true
          schema:
            type: string
            enum: [excellent, very good, good, fair, poor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LtcQueryRequiredInput"
      responses:
        "200":
          description: Predicted probability distribution for long-term care
          content:
            application/json:
              schema:
                type: object
                properties:
                  ltc_need_proba:
                    type: object
                    properties:
                      proba_mean:
                        type: number
                        example: 64
                      proba_std:
                        type: number
                        example: 13
                      count:
                        type: integer
                        example: 10000
                      unit:
                        type: string
                        example: "%"
        "400":
          description: Invalid request body
        "500":
          description: Internal server error
  /ltc/queries/type:
    post:
      tags: [LTC Queries]
      summary: Estimate long-term care service type probabilities
      description: Predicts probabilities for different types of long-term care services.
      operationId: queryServiceType
      parameters:
        - name: age
          in: query
          required: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          schema:
            type: string
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
        - name: overall_health_rating
          in: query
          required: true
          schema:
            type: string
            enum: [excellent, very good, good, fair, poor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LtcQueryRequiredInput"
      responses:
        "200":
          description: Predicted service type distribution for long-term care
          content:
            application/json:
              schema:
                type: object
                properties:
                  ltc_service_type_proba:
                    type: object
                    properties:
                      homeHealthCare:
                        type: object
                        properties:
                          proba_mean:
                            type: number
                            example: 17
                          proba_std:
                            type: number
                            example: 15
                      assistedLivingFacility:
                        type: object
                        properties:
                          proba_mean:
                            type: number
                            example: 83
                          proba_std:
                            type: number
                            example: 15
                      nursingHome:
                        type: object
                        properties:
                          proba_mean:
                            type: number
                            example: 0
                          proba_std:
                            type: number
                            example: 0
                      count:
                        type: integer
                        example: 10000
                      unit:
                        type: string
                        example: "%"
        "400":
          description: Invalid request body
        "500":
          description: Internal server error
  /ltc/queries/cost:
    post:
      tags: [LTC Queries]
      summary: Estimate long-term care costs
      description: Predicts cost distribution for long-term care.
      operationId: queryCost
      parameters:
        - name: age
          in: query
          required: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          schema:
            type: string
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
        - name: overall_health_rating
          in: query
          required: true
          schema:
            type: string
            enum: [excellent, very good, good, fair, poor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LtcQueryRequiredInput"
      responses:
        "200":
          description: Predicted cost distribution for long-term care
          content:
            application/json:
              schema:
                type: object
                properties:
                  hc_cost:
                    type: object
                    properties:
                      cost_mean:
                        type: array
                        items:
                          type: number
                        example:
                          [560, 1170, 1870, 2690, 3640, 4810, 6320, 8450, 12080]
                      cost_std:
                        type: array
                        items:
                          type: number
                        example: [30, 60, 100, 140, 190, 250, 330, 440, 620]
                      proba:
                        type: array
                        items:
                          type: number
                        example: [90, 80, 70, 60, 50, 40, 29, 19, 10]
                      count:
                        type: integer
                        example: 10000
        "400":
          description: Invalid request body
        "500":
          description: Internal server error
  /ltc/queries/duration:
    post:
      tags: [LTC Queries]
      summary: Estimate long-term care duration
      description: Predicts the duration of long-term care usage.
      operationId: queryDuration
      parameters:
        - name: age
          in: query
          required: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          schema:
            type: string
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
        - name: overall_health_rating
          in: query
          required: true
          schema:
            type: string
            enum: [excellent, very good, good, fair, poor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LtcQueryRequiredInput"
      responses:
        "200":
          description: Predicted duration distribution for long-term care
          content:
            application/json:
              schema:
                type: object
                properties:
                  hc_duration:
                    type: object
                    properties:
                      duration_mean:
                        type: array
                        items:
                          type: number
                        example: [1, 2, 3, 4, 5]
                      duration_std:
                        type: array
                        items:
                          type: number
                        example: [0.5, 0.7, 1.0, 1.2, 1.5]
                      proba:
                        type: array
                        items:
                          type: number
                        example: [90, 75, 60, 45, 30]
                      count:
                        type: integer
                        example: 10000
        "400":
          description: Invalid request body
        "500":
          description: Internal server error
  /ltc/queries/longevity:
    post:
      tags: [LTC Queries]
      summary: Estimate longevity distribution
      description: Predicts age-based longevity probabilities.
      operationId: queryLongevity
      parameters:
        - name: age
          in: query
          required: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          schema:
            type: string
        - name: zipcode
          in: query
          required: true
          schema:
            type: string
        - name: overall_health_rating
          in: query
          required: true
          schema:
            type: string
            enum: [excellent, very good, good, fair, poor]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LtcQueryRequiredInput"
      responses:
        "200":
          description: Predicted longevity distribution for long-term care
          content:
            application/json:
              schema:
                type: object
                properties:
                  longevity:
                    type: object
                    properties:
                      age_mean:
                        type: array
                        items:
                          type: number
                        example: [74, 78, 81, 84, 86, 88, 90, 92, 95]
                      age_std:
                        type: array
                        items:
                          type: number
                        example: [2, 3, 3, 3, 3, 3, 3, 3, 2]
                      proba:
                        type: array
                        items:
                          type: number
                        example: [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
        "400":
          description: Invalid request body
        "500":
          description: Internal server error
components:
  schemas:
    Client:
      type: object
      properties:
        last_updated:
          type: string
          format: date-time
        advisor_id:
          type: string
          format: uuid
        last_name:
          type: string
        first_name:
          type: string
        created:
          type: string
          format: date-time
        phone_number:
          type: string
        is_active:
          type: boolean
        user_role:
          type: string
          enum:
            - client
        email:
          type: string
          format: email
        id:
          type: string
          format: uuid
        scenarios:
          type: array
          items:
            type: object
        dependents:
          type: array
          items:
            type: object
      required:
        - last_updated
        - advisor_id
        - last_name
        - first_name
        - created
        - is_active
        - user_role
        - email
        - id
        - scenarios
        - dependents
    Advisor:
      type: object
      properties:
        last_updated:
          type: string
          format: date-time
        last_name:
          type: string
        user_role:
          type: string
          enum:
            - advisor
        email:
          type: string
          format: email
        id:
          type: string
          format: uuid
        first_name:
          type: string
      required:
        - last_updated
        - last_name
        - user_role
        - email
        - id
        - first_name
    LtcQueryRequiredInput:
      type: object
      required:
        - age
        - gender
        - zipcode
        - overall_health_rating
      properties:
        age:
          type: integer
        gender:
          type: string
        zipcode:
          type: string
        overall_health_rating:
          type: string
          enum: [excellent, very good, good, fair, poor]
